- uses: actions/checkout@v4

- name: Show repo tree and Dockerfile (debug)
  run: |
    pwd
    ls -la
    echo "---- Dockerfile (head) ----"
    head -n 60 Dockerfile || true

- name: Build and push Docker image
  uses: docker/build-push-action@v5
  with:
    context: .
    file: ./Dockerfile          # <— explicit
    push: true
    no-cache: true              # <— avoid using old cached Dockerfile
    tags: |
      beekay123/tf2-discord-scoreboard:latest
      beekay123/tf2-discord-scoreboard:${{ github.ref_name }}
