name: Publish Docker image

on:
  push:
    branches: [ "main" ]   # build/push latest on every push to main
  release:
    types: [published]     # also build/push a version tag on release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure secrets are set
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_USERNAME or DOCKERHUB_TOKEN secret not set!"
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tf2-discord-scoreboard:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tf2-discord-scoreboard:${{ github.ref_name }}
